# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Söllner's Blog
email: benjamin.soellner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Benjamin Söllner - multimedia computer scientist, integrator of
  data, IT and people, social dancer, amateur photographer and
  outdoor globetrotter. This is a blog about all interesting
  things I search and find.
baseurl: "" # the subpath of your site, e.g. /blog
picturl: "/assets/picture.jpg"
url: "http://benjaminsoellner.github.io" # the base hostname & protocol for your site

linkedin_username: benjaminsoellner
github_username: benjaminsoellner
academia_username: BenjaminSoellner
twitter_username: qwertzuhr
flickr_username: unclebenjamin
flickr_id: 61423571@N00

links: [
    {
       title: Resume,
       url: /assets/resume.pdf
    }
]

# Build settings
markdown: kramdown
